{
	"version": 1722448036,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ceu.png",
		"images/robo-sheet0.png",
		"images/fundo-sheet0.png",
		"images/minibo-sheet0.png",
		"images/minibo-sheet1.png",
		"images/minibo-sheet2.png",
		"images/tilebackground.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/fundopontos-sheet0.png",
		"images/final-sheet0.png",
		"images/final-sheet1.png",
		"images/final-sheet2.png",
		"images/abelha-sheet0.png",
		"images/abelha-sheet1.png",
		"images/tampolim-sheet0.png",
		"images/tampolim-sheet1.png",
		"images/zombie2-sheet0.png",
		"images/zombie2-sheet1.png",
		"images/zombie2-sheet2.png",
		"images/plataforma_verde.png",
		"images/botao_verde-sheet0.png",
		"images/botao_verde-sheet1.png",
		"images/qualquercoisa-sheet0.png",
		"images/aa.png",
		"images/chao_amarelo.png",
		"images/plataforma_amarelo.png",
		"images/botao_amarelo-sheet0.png",
		"images/botao_amarelo-sheet1.png",
		"images/portal01-sheet0.png",
		"images/portal02-sheet0.png",
		"images/portal03-sheet0.png",
		"images/portal04-sheet0.png",
		"images/inimigo02-sheet0.png",
		"images/inimigo02-sheet1.png",
		"images/outracoisa-sheet0.png",
		"images/chao2.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground6.png",
		"images/tiledbackground7.png",
		"images/tiledbackground9.png",
		"images/popup-sheet0.png",
		"images/pop-sheet0.png",
		"images/sprite-sheet0.png",
		"images/over-sheet0.png",
		"images/restart-sheet0.png",
		"images/restart2-sheet0.png",
		"images/bgplay-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/button-sheet0.png",
		"images/button2-sheet0.png",
		"images/level-sheet0.png",
		"images/spritefont.png",
		"images/spritefont3.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/tiledbackground10.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"media/rainbow forest - quincas moreira.m4a",
		"media/rainbow forest - quincas moreira.ogg",
		"media/coins shuffling.m4a",
		"media/coins shuffling.ogg",
		"media/hand claps far.m4a",
		"media/hand claps far.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}